server:
  port: 3001
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: auth-service
  mongodb:
    uri: ${MONGO_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry: 900000        # 15 minutes in milliseconds
    refresh-token-expiry: 604800000    # 7 days in milliseconds