server:
  port: 3001

spring:
  application:
    name: auth-service
  mongodb:
    uri: ${MONGO_URI}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry: 900000        # 15 minutes in milliseconds
    refresh-token-expiry: 604800000    # 7 days in milliseconds