spring:
  application:
    name: notification-service

  # autoconfigure:
  #   exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  data:
    mongodb:
      uri: ${MONGO_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 3007

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:ACc11802990a504f7e3d7d46f28e0418c4}
  auth-token: ${TWILIO_AUTH_TOKEN:288e669579485982aad5c6ac8f35ea09}
  phone-number: ${TWILIO_PHONE_NUMBER:+16627044273}

# sendgrid:
#   api-key: ${SENDGRID_API_KEY:}
#   from-email: ${SENDGRID_FROM_EMAIL:kaveeshasandeepani027@gmail.com}
#   from-name: ${SENDGRID_FROM_NAME:aferent}

# resend:
#   api-key: ${RESEND_API_KEY:re_7rQaWBPW_34VButynyDhq6BCCEkppXxmz}
#   from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
#   from-name: ${RESEND_FROM_NAME:Smart Healthcare Platform}


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

notification:
  mail:
    from-name: ${GMAIL_FROM_NAME}